// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: gRaosoDicn4VUCndSzazbA
// Component: PlpIcihQhaX91
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavMenu from "../../NavMenu"; // plasmic-import: 9cR2sxpykRjad/component
import ScenesTagMenuBtn from "../../ScenesTagMenuBtn"; // plasmic-import: slY9K5ec7o/component
import SceneInfo from "../../SceneInfo"; // plasmic-import: Zf1zYQ7YK23by/component
import Toolbar from "../../Toolbar"; // plasmic-import: UlyQXoohOO/component
import { useScreenVariants as useScreenVariantsnl9I0Oib3VOwY } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: nl9_I0oib3VOwY/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic_plasmic_rich_components.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic_chats_client.module.css"; // plasmic-import: gRaosoDicn4VUCndSzazbA/projectcss
import sty from "./PlasmicWorkspaces.module.css"; // plasmic-import: PlpIcihQhaX91/css
import Icon15Icon from "./icons/PlasmicIcon__Icon15"; // plasmic-import: HpyYmDJCsB/icon

export const PlasmicWorkspaces__VariantProps = new Array();

export const PlasmicWorkspaces__ArgProps = new Array("grid");

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicWorkspaces__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsnl9I0Oib3VOwY()
  });
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicWorkspaces.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicWorkspaces.pageMetadata.title}
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicWorkspaces.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          {true ? (
            <div
              data-plasmic-name={"bkgd"}
              data-plasmic-override={overrides.bkgd}
              className={classNames(projectcss.all, sty.bkgd)}
            >
              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <NavMenu
                  data-plasmic-name={"navMenu"}
                  data-plasmic-override={overrides.navMenu}
                  className={classNames("__wab_instance", sty.navMenu)}
                  menu1={true}
                />
              ) : null}
              <section
                data-plasmic-name={"section"}
                data-plasmic-override={overrides.section}
                className={classNames(projectcss.all, sty.section)}
              >
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__xEHmj)}
                  >
                    {true ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___9MNcR
                        )}
                      >
                        {(
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? true
                            : true
                        ) ? (
                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"tabTitle"}
                            data-plasmic-override={overrides.tabTitle}
                            hasGap={true}
                            className={classNames(projectcss.all, sty.tabTitle)}
                          >
                            <Icon15Icon
                              data-plasmic-name={"svg"}
                              data-plasmic-override={overrides.svg}
                              className={classNames(projectcss.all, sty.svg)}
                              role={"img"}
                            />

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___1Lu3A
                              )}
                            >
                              {"场景分类"}
                            </div>
                          </p.Stack>
                        ) : null}
                        <p.Stack
                          as={"aside"}
                          data-plasmic-name={"scenesTabs"}
                          data-plasmic-override={overrides.scenesTabs}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.scenesTabs,
                            ``
                          )}
                          id={"scenes_tag"}
                          tabIndex={1}
                        >
                          <ScenesTagMenuBtn
                            className={classNames(
                              "__wab_instance",
                              sty.scenesTagMenuBtn__sC6Sx
                            )}
                            isActive={true}
                          />

                          <ScenesTagMenuBtn
                            className={classNames(
                              "__wab_instance",
                              sty.scenesTagMenuBtn__xJv31
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___541Oa
                              )}
                            >
                              {"热门"}
                            </div>
                          </ScenesTagMenuBtn>
                          <ScenesTagMenuBtn
                            className={classNames(
                              "__wab_instance",
                              sty.scenesTagMenuBtn__l1UmW
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__zhIp
                              )}
                            >
                              {"小红书营销类"}
                            </div>
                          </ScenesTagMenuBtn>
                          <ScenesTagMenuBtn
                            className={classNames(
                              "__wab_instance",
                              sty.scenesTagMenuBtn__dObK
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__qt2Yg
                              )}
                            >
                              {"出题机"}
                            </div>
                          </ScenesTagMenuBtn>
                          <ScenesTagMenuBtn
                            className={classNames(
                              "__wab_instance",
                              sty.scenesTagMenuBtn__nuhil
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__lIPvv
                              )}
                            >
                              {"中文社交媒体"}
                            </div>
                          </ScenesTagMenuBtn>
                          <ScenesTagMenuBtn
                            className={classNames(
                              "__wab_instance",
                              sty.scenesTagMenuBtn___8Jcxy
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__lqRom
                              )}
                            >
                              {"全部"}
                            </div>
                          </ScenesTagMenuBtn>
                        </p.Stack>
                        {(
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? true
                            : true
                        ) ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__aWlrv
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__li5Gw
                              )}
                            >
                              {"剩余字数\n19280 字"}
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ieywc
                              )}
                            >
                              {"用户小黄帽"}
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___2Ov4U
                              )}
                            >
                              {"免费用户"}
                            </div>
                          </div>
                        ) : null}
                      </div>
                    ) : null}
                    {true ? (
                      <div
                        data-plasmic-name={"columns"}
                        data-plasmic-override={overrides.columns}
                        className={classNames(projectcss.all, sty.columns)}
                      >
                        <div
                          data-plasmic-name={"column"}
                          data-plasmic-override={overrides.column}
                          className={classNames(projectcss.all, sty.column)}
                        >
                          <div
                            data-plasmic-name={"grid"}
                            data-plasmic-override={overrides.grid}
                            className={classNames(projectcss.all, sty.grid)}
                          >
                            {p.renderPlasmicSlot({
                              defaultContents: (
                                <React.Fragment>
                                  <SceneInfo
                                    className={classNames(
                                      "__wab_instance",
                                      sty.sceneInfo__zigmA
                                    )}
                                    desc={
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__lYmX8
                                        )}
                                      >
                                        {
                                          "小红书营销专用，网络社区小红书博主风格的语气"
                                        }
                                      </div>
                                    }
                                    input={
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__u2GgT
                                        )}
                                      >
                                        {"Modal content"}
                                      </div>
                                    }
                                    output={"Modal content"}
                                    title={
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__miKH
                                        )}
                                      >
                                        {"小红书营销短文和语气"}
                                      </div>
                                    }
                                  />

                                  <SceneInfo
                                    className={classNames(
                                      "__wab_instance",
                                      sty.sceneInfo__ok60U
                                    )}
                                    desc={"desc"}
                                    input={
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__kCFbv
                                        )}
                                      >
                                        {"Modal content"}
                                      </div>
                                    }
                                    output={"Modal content"}
                                    title={"场景标题"}
                                  />

                                  <SceneInfo
                                    className={classNames(
                                      "__wab_instance",
                                      sty.sceneInfo__qdlmq
                                    )}
                                    desc={"desc"}
                                    input={
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__hx7T0
                                        )}
                                      >
                                        {"Modal content"}
                                      </div>
                                    }
                                    output={"Modal content"}
                                    title={"场景标题"}
                                  />

                                  <SceneInfo
                                    className={classNames(
                                      "__wab_instance",
                                      sty.sceneInfo__dtd5A
                                    )}
                                    desc={"desc"}
                                    input={
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__cvTn8
                                        )}
                                      >
                                        {"Modal content"}
                                      </div>
                                    }
                                    output={"Modal content"}
                                    title={"场景标题"}
                                  />

                                  <SceneInfo
                                    className={classNames(
                                      "__wab_instance",
                                      sty.sceneInfo__bu96
                                    )}
                                    desc={"desc"}
                                    input={
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__rgGA
                                        )}
                                      >
                                        {"Modal content"}
                                      </div>
                                    }
                                    output={"Modal content"}
                                    title={"场景标题"}
                                  />

                                  <SceneInfo
                                    className={classNames(
                                      "__wab_instance",
                                      sty.sceneInfo__maa04
                                    )}
                                    desc={"desc"}
                                    input={
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__pBRxc
                                        )}
                                      >
                                        {"Modal content"}
                                      </div>
                                    }
                                    output={"Modal content"}
                                    title={"场景标题"}
                                  />

                                  <SceneInfo
                                    className={classNames(
                                      "__wab_instance",
                                      sty.sceneInfo__dKhQ2
                                    )}
                                    desc={"desc"}
                                    input={
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__dLcox
                                        )}
                                      >
                                        {"Modal content"}
                                      </div>
                                    }
                                    output={"Modal content"}
                                    title={"场景标题"}
                                  />
                                </React.Fragment>
                              ),

                              value: args.grid
                            })}
                          </div>
                        </div>
                      </div>
                    ) : null}
                  </p.Stack>
                ) : null}
              </section>
            </div>
          ) : null}
          {(
            hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
          ) ? (
            <Toolbar
              data-plasmic-name={"toolbar"}
              data-plasmic-override={overrides.toolbar}
              className={classNames("__wab_instance", sty.toolbar)}
              tab1={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? true
                  : undefined
              }
            />
          ) : null}
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "bkgd",
    "navMenu",
    "section",
    "tabTitle",
    "svg",
    "scenesTabs",
    "columns",
    "column",
    "grid",
    "toolbar"
  ],

  bkgd: [
    "bkgd",
    "navMenu",
    "section",
    "tabTitle",
    "svg",
    "scenesTabs",
    "columns",
    "column",
    "grid"
  ],

  navMenu: ["navMenu"],
  section: [
    "section",
    "tabTitle",
    "svg",
    "scenesTabs",
    "columns",
    "column",
    "grid"
  ],

  tabTitle: ["tabTitle", "svg"],
  svg: ["svg"],
  scenesTabs: ["scenesTabs"],
  columns: ["columns", "column", "grid"],
  column: ["column", "grid"],
  grid: ["grid"],
  toolbar: ["toolbar"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicWorkspaces__ArgProps,
          internalVariantPropNames: PlasmicWorkspaces__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicWorkspaces__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicWorkspaces";
  } else {
    func.displayName = `PlasmicWorkspaces.${nodeName}`;
  }
  return func;
}

export const PlasmicWorkspaces = Object.assign(
  // Top-level PlasmicWorkspaces renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    bkgd: makeNodeComponent("bkgd"),
    navMenu: makeNodeComponent("navMenu"),
    section: makeNodeComponent("section"),
    tabTitle: makeNodeComponent("tabTitle"),
    svg: makeNodeComponent("svg"),
    scenesTabs: makeNodeComponent("scenesTabs"),
    columns: makeNodeComponent("columns"),
    column: makeNodeComponent("column"),
    grid: makeNodeComponent("grid"),
    toolbar: makeNodeComponent("toolbar"),
    // Metadata about props expected for PlasmicWorkspaces
    internalVariantProps: PlasmicWorkspaces__VariantProps,
    internalArgProps: PlasmicWorkspaces__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "工作台",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicWorkspaces;
/* prettier-ignore-end */
