// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: gRaosoDicn4VUCndSzazbA
// Component: AAi9AuCCbMra
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import { useDependencyAwareQuery } from "@plasmicapp/react-web/lib/data-sources";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: YO5Bwb9purCqu/component
import Price from "../../Price"; // plasmic-import: A7lxlJD3kKn/component
import { useScreenVariants as useScreenVariantsnl9I0Oib3VOwY } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: nl9_I0oib3VOwY/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_chats_client.module.css"; // plasmic-import: gRaosoDicn4VUCndSzazbA/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: AAi9AuCCbMra/css
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: JhZ3dtt_5DRD2s/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: AO1hQKEExk65Hm/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: A0Me8Phykv/icon
import Icon7Icon from "./icons/PlasmicIcon__Icon7"; // plasmic-import: P8LQPjDHPd/icon
import Icon14Icon from "./icons/PlasmicIcon__Icon14"; // plasmic-import: MTyawrbN6uF/icon
import Icon8Icon from "./icons/PlasmicIcon__Icon8"; // plasmic-import: WYrTsWzQKYW/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: KoY309Tgrjk/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: IzwKr9-s2sD/icon
import Icon28Icon from "./icons/PlasmicIcon__Icon28"; // plasmic-import: Pu_bRg2PBqC/icon

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "textbox.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ``
      },
      {
        path: "textbox2.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ``
      },
      {
        path: "textbox3.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ``
      },
      {
        path: "textbox.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ``
      },
      {
        path: "textbox2.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ``
      },
      {
        path: "textbox3.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ``
      },
      {
        path: "textbox.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ``
      },
      {
        path: "textbox2.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ``
      },
      {
        path: "textbox3.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ``
      }
    ],

    [$props, $ctx]
  );
  const $state = p.useDollarState(stateSpecs, { $props, $ctx, $queries });
  useDependencyAwareQuery({
    name: "query",
    getDataOp: () => ({
      sourceId: "9m6seF9rffTwqmNeTPj4dy",
      opId: "76d162da-e80e-4bfc-82eb-27018f41acaf",
      userArgs: {},
      cacheKey: "plasmic.$.AXV5MeQQE3xu.$.",
      invalidatedKeys: ["plasmic_refresh_all"],
      roleId: null
    }),
    $queries,
    setDollarQueries
  });
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsnl9I0Oib3VOwY()
  });
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{PlasmicHomepage.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicHomepage.pageMetadata.title}
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicHomepage.pageMetadata.title}
        />

        <meta
          key="description"
          name="description"
          content={PlasmicHomepage.pageMetadata.description}
        />

        <meta
          key="og:description"
          property="og:description"
          content={PlasmicHomepage.pageMetadata.description}
        />

        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicHomepage.pageMetadata.description}
        />

        <meta
          key="og:image"
          property="og:image"
          content={PlasmicHomepage.pageMetadata.ogImageSrc}
        />

        <meta
          key="twitter:image"
          name="twitter:image"
          content={PlasmicHomepage.pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__vTrh4)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__qnDkJ)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__u2Shq)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___6Olc6)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"200px"}
                  src={{
                    src: "/plasmic/chats_client/images/logofull2Xpng.png",
                    fullWidth: 346,
                    fullHeight: 96,
                    aspectRatio: undefined
                  }}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__sXpnp)}
                >
                  <Button
                    className={classNames("__wab_instance", sty.button__edLoX)}
                    color={"clear"}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__l4HSf)}
                        role={"img"}
                      />
                    }
                    onClick={async event => {
                      const $steps = {};
                      $steps["goToDescValue"] = true
                        ? (() => {
                            const actionArgs = {
                              destination: __wrapUserFunction(
                                {
                                  type: "InteractionArgLoc",
                                  actionName: "navigation",
                                  interactionUuid: "uPeGkQxTT",
                                  componentUuid: "AAi9AuCCbMra",
                                  argName: "destination"
                                },
                                () => "/#desc-value"
                              )
                            };
                            return __wrapUserFunction(
                              {
                                type: "InteractionLoc",
                                actionName: "navigation",
                                interactionUuid: "uPeGkQxTT",
                                componentUuid: "AAi9AuCCbMra"
                              },
                              () =>
                                (({ destination }) => {
                                  __nextRouter?.push(destination);
                                })?.apply(null, [actionArgs]),
                              actionArgs
                            );
                          })()
                        : undefined;
                      if (
                        typeof $steps["goToDescValue"] === "object" &&
                        typeof $steps["goToDescValue"].then === "function"
                      ) {
                        $steps["goToDescValue"] = await __wrapUserPromise(
                          {
                            type: "InteractionLoc",
                            actionName: "navigation",
                            interactionUuid: "uPeGkQxTT",
                            componentUuid: "AAi9AuCCbMra"
                          },
                          $steps["goToDescValue"]
                        );
                      }
                    }}
                    startIcon={
                      <ChecksvgIcon
                        className={classNames(projectcss.all, sty.svg__bz3MI)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yGBgA
                      )}
                    >
                      {"使用说明"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__lwQFu)}
                    color={"clear"}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__nj7SK)}
                        role={"img"}
                      />
                    }
                    onClick={async event => {
                      const $steps = {};
                      $steps["goToPriceCard"] = true
                        ? (() => {
                            const actionArgs = {
                              destination: __wrapUserFunction(
                                {
                                  type: "InteractionArgLoc",
                                  actionName: "navigation",
                                  interactionUuid: "DLyvrAo77",
                                  componentUuid: "AAi9AuCCbMra",
                                  argName: "destination"
                                },
                                () => "/#price-card"
                              )
                            };
                            return __wrapUserFunction(
                              {
                                type: "InteractionLoc",
                                actionName: "navigation",
                                interactionUuid: "DLyvrAo77",
                                componentUuid: "AAi9AuCCbMra"
                              },
                              () =>
                                (({ destination }) => {
                                  __nextRouter?.push(destination);
                                })?.apply(null, [actionArgs]),
                              actionArgs
                            );
                          })()
                        : undefined;
                      if (
                        typeof $steps["goToPriceCard"] === "object" &&
                        typeof $steps["goToPriceCard"].then === "function"
                      ) {
                        $steps["goToPriceCard"] = await __wrapUserPromise(
                          {
                            type: "InteractionLoc",
                            actionName: "navigation",
                            interactionUuid: "DLyvrAo77",
                            componentUuid: "AAi9AuCCbMra"
                          },
                          $steps["goToPriceCard"]
                        );
                      }
                    }}
                    startIcon={
                      <ChecksvgIcon
                        className={classNames(projectcss.all, sty.svg__gHyel)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rdeBy
                      )}
                    >
                      {"价格"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__fDDk1)}
                    color={"clear"}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__f9CPs)}
                        role={"img"}
                      />
                    }
                    onClick={async event => {
                      const $steps = {};
                      $steps["goToAboutus"] = true
                        ? (() => {
                            const actionArgs = {
                              destination: __wrapUserFunction(
                                {
                                  type: "InteractionArgLoc",
                                  actionName: "navigation",
                                  interactionUuid: "t9EyezZeT",
                                  componentUuid: "AAi9AuCCbMra",
                                  argName: "destination"
                                },
                                () => "/aboutus"
                              )
                            };
                            return __wrapUserFunction(
                              {
                                type: "InteractionLoc",
                                actionName: "navigation",
                                interactionUuid: "t9EyezZeT",
                                componentUuid: "AAi9AuCCbMra"
                              },
                              () =>
                                (({ destination }) => {
                                  __nextRouter?.push(destination);
                                })?.apply(null, [actionArgs]),
                              actionArgs
                            );
                          })()
                        : undefined;
                      if (
                        typeof $steps["goToAboutus"] === "object" &&
                        typeof $steps["goToAboutus"].then === "function"
                      ) {
                        $steps["goToAboutus"] = await __wrapUserPromise(
                          {
                            type: "InteractionLoc",
                            actionName: "navigation",
                            interactionUuid: "t9EyezZeT",
                            componentUuid: "AAi9AuCCbMra"
                          },
                          $steps["goToAboutus"]
                        );
                      }
                    }}
                    startIcon={
                      <ChecksvgIcon
                        className={classNames(projectcss.all, sty.svg___3NgSh)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kNtlw
                      )}
                    >
                      {"关于我们"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__a1X34)}
                    color={"green"}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__kzRcy)}
                        role={"img"}
                      />
                    }
                    link={`/workspaces`}
                    startIcon={
                      <ChecksvgIcon
                        className={classNames(projectcss.all, sty.svg__nrmNp)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___0U4Qk
                      )}
                    >
                      {"免费注册"}
                    </div>
                  </Button>
                </p.Stack>
                {false ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mvYgQ)}
                  >
                    <button
                      className={classNames(
                        projectcss.all,
                        projectcss.button,
                        projectcss.__wab_text,
                        sty.button___8Xvrc
                      )}
                    >
                      {"Sign up"}
                    </button>
                    {true ? (
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button___2R0VD
                        )}
                        color={"clear"}
                        endIcon={
                          <IconIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__pQht0
                            )}
                            role={"img"}
                          />
                        }
                        startIcon={
                          <ChecksvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___9VItp
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__usbzz
                          )}
                        >
                          {"Log in"}
                        </div>
                      </Button>
                    ) : null}
                  </div>
                ) : null}
              </p.Stack>
            </p.Stack>
          </div>
          <p.Stack
            as={"div"}
            data-plasmic-name={"foreground"}
            data-plasmic-override={overrides.foreground}
            hasGap={true}
            className={classNames(projectcss.all, sty.foreground)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__ruOkm)}
            >
              {true ? (
                <div className={classNames(projectcss.all, sty.freeBox__eq44B)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__vzl5)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "auto"
                        : "337px"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "45%"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/chats_client/images/headerpng.png",
                      fullWidth: 1000,
                      fullHeight: 733,
                      aspectRatio: undefined
                    }}
                  />

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__dw9Bx)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pIBiS
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#D77A00" }}
                        >
                          {"机智桔子 "}
                        </span>
                        <React.Fragment>
                          {"\n您的智能AI时代好助手！"}
                        </React.Fragment>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__efmCb
                      )}
                    >
                      {"AI不会取代我们，使用AI会让我们走的更远..."}
                    </div>
                  </p.Stack>
                </div>
              ) : null}
            </p.Stack>
            <p.Stack
              as={"div"}
              data-plasmic-name={"login"}
              data-plasmic-override={overrides.login}
              hasGap={true}
              className={classNames(projectcss.all, sty.login)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__fdw14)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__r532S)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__gbZ50)}
                  >
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__uIxf0
                      )}
                      color={"white"}
                      endIcon={
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__anZa)}
                          role={"img"}
                        />
                      }
                      showStartIcon={true}
                      startIcon={
                        <Icon5Icon
                          className={classNames(projectcss.all, sty.svg__yX2De)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__la2Kz
                        )}
                      >
                        {"邮箱注册"}
                      </div>
                    </Button>
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__movWt
                      )}
                      color={"white"}
                      endIcon={
                        <IconIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___60MOu
                          )}
                          role={"img"}
                        />
                      }
                      showStartIcon={true}
                      startIcon={
                        <Icon7Icon
                          className={classNames(projectcss.all, sty.svg__livc9)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zNjbG
                        )}
                      >
                        {"手机注册"}
                      </div>
                    </Button>
                  </p.Stack>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__uVbLd)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox___8W4)}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yMRf
                      )}
                    >
                      {"登录"}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__jnwzj)}
                    />
                  </p.Stack>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__zDgSk)}
                  >
                    <input
                      data-plasmic-name={"textbox"}
                      data-plasmic-override={overrides.textbox}
                      className={classNames(
                        projectcss.all,
                        projectcss.input,
                        sty.textbox
                      )}
                      onChange={e => {
                        p.generateStateOnChangeProp($state, [
                          "textbox",
                          "value"
                        ])(e.target.value);
                      }}
                      placeholder={"邮箱/手机号"}
                      ref={ref => {
                        $refs["textbox"] = ref;
                      }}
                      size={1}
                      type={"text"}
                      value={p.generateStateValueProp($state, [
                        "textbox",
                        "value"
                      ])}
                    />

                    <input
                      data-plasmic-name={"textbox2"}
                      data-plasmic-override={overrides.textbox2}
                      className={classNames(
                        projectcss.all,
                        projectcss.input,
                        sty.textbox2
                      )}
                      onChange={e => {
                        p.generateStateOnChangeProp($state, [
                          "textbox2",
                          "value"
                        ])(e.target.value);
                      }}
                      placeholder={"输入密码"}
                      ref={ref => {
                        $refs["textbox2"] = ref;
                      }}
                      size={1}
                      type={"password"}
                      value={p.generateStateValueProp($state, [
                        "textbox2",
                        "value"
                      ])}
                    />

                    <input
                      data-plasmic-name={"textbox3"}
                      data-plasmic-override={overrides.textbox3}
                      className={classNames(
                        projectcss.all,
                        projectcss.input,
                        sty.textbox3
                      )}
                      onChange={e => {
                        p.generateStateOnChangeProp($state, [
                          "textbox3",
                          "value"
                        ])(e.target.value);
                      }}
                      placeholder={"验证码"}
                      ref={ref => {
                        $refs["textbox3"] = ref;
                      }}
                      size={1}
                      type={"text"}
                      value={p.generateStateValueProp($state, [
                        "textbox3",
                        "value"
                      ])}
                    />
                  </p.Stack>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__feud5
                    )}
                  >
                    {"请阅读用户隐私协议"}
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button__c5DC0)}
                    color={"green"}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__vrQ0S)}
                        role={"img"}
                      />
                    }
                    link={`/myaccount`}
                    onClick={async event => {
                      const $steps = {};
                      $steps["goToWorkspace"] = true
                        ? (() => {
                            const actionArgs = {};
                            return __wrapUserFunction(
                              {
                                type: "InteractionLoc",
                                actionName: "navigation",
                                interactionUuid: "jtc46TirU",
                                componentUuid: "AAi9AuCCbMra"
                              },
                              () =>
                                (({ destination }) => {
                                  __nextRouter?.push(destination);
                                })?.apply(null, [actionArgs]),
                              actionArgs
                            );
                          })()
                        : undefined;
                      if (
                        typeof $steps["goToWorkspace"] === "object" &&
                        typeof $steps["goToWorkspace"].then === "function"
                      ) {
                        $steps["goToWorkspace"] = await __wrapUserPromise(
                          {
                            type: "InteractionLoc",
                            actionName: "navigation",
                            interactionUuid: "jtc46TirU",
                            componentUuid: "AAi9AuCCbMra"
                          },
                          $steps["goToWorkspace"]
                        );
                      }
                    }}
                    startIcon={
                      <ChecksvgIcon
                        className={classNames(projectcss.all, sty.svg__lkGa)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yfUb
                      )}
                    >
                      {"登录"}
                    </div>
                  </Button>
                </p.Stack>
              </div>
            </p.Stack>
          </p.Stack>
          {true ? (
            <div className={classNames(projectcss.all, sty.freeBox__qfCrU)}>
              <section
                data-plasmic-name={"value"}
                data-plasmic-override={overrides.value}
                className={classNames(projectcss.all, sty.value)}
                id={"desc-value"}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"foreground4"}
                  data-plasmic-override={overrides.foreground4}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.foreground4)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___72Cv)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__l5Mxs)}
                    >
                      <h2
                        data-plasmic-name={"h2"}
                        data-plasmic-override={overrides.h2}
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2
                        )}
                      >
                        {"智能掌握，高效写作"}
                      </h2>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___5Mw
                        )}
                      >
                        {
                          "帮助您提高工作效率，节约时间和精力，同时提高文章质量和发掘更多独到创意"
                        }
                      </div>
                    </div>
                  </p.Stack>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__pnErq)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__wj0Iy)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__k8BRz
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__gIlWv
                          )}
                        >
                          <Icon14Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__xWo1H
                            )}
                            role={"img"}
                          />
                        </div>
                        {false ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__koAi
                            )}
                          >
                            <Icon8Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__s3Gy
                              )}
                              role={"img"}
                            />
                          </div>
                        ) : null}
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__lWn4O
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__aDzfr
                            )}
                          >
                            {"新的效率"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__acCkg
                            )}
                          >
                            {
                              "通过使用人工智能技术来自动生成文章和文档，从而大大节省创作时间。"
                            }
                          </div>
                        </p.Stack>
                      </p.Stack>
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__mRSkl
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__qMww
                          )}
                        >
                          <Icon14Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___3Cgqe
                            )}
                            role={"img"}
                          />
                        </div>
                        {false ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__lM2WS
                            )}
                          >
                            <Icon8Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__ifn3J
                              )}
                              role={"img"}
                            />
                          </div>
                        ) : null}
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__o3UTj
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__wGTo
                            )}
                          >
                            {"优化文章质量"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___036Ah
                            )}
                          >
                            {
                              "强大功能可提供文本分析、结构分析、语法检查等服务，帮助提升文章质量"
                            }
                          </div>
                        </p.Stack>
                      </p.Stack>
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__sfWlx
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__whIH
                          )}
                        >
                          <Icon14Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__nbUyu
                            )}
                            role={"img"}
                          />
                        </div>
                        {false ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__jAAvD
                            )}
                          >
                            <Icon8Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__ykmo0
                              )}
                              role={"img"}
                            />
                          </div>
                        ) : null}
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__lXxi0
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__enbcG
                            )}
                          >
                            {"随叫随到"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__jeQnA
                            )}
                          >
                            {
                              "24小时不间断的写作助手，您可以随时使用，而无需担心工作时间和地点等限制。"
                            }
                          </div>
                        </p.Stack>
                      </p.Stack>
                    </p.Stack>
                  </p.Stack>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__dhLou)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__sycim)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__l1Y79
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__jiJyo
                          )}
                        >
                          <Icon14Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__fu7BA
                            )}
                            role={"img"}
                          />
                        </div>
                        {false ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__a8BR9
                            )}
                          >
                            <Icon8Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__bseyL
                              )}
                              role={"img"}
                            />
                          </div>
                        ) : null}
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__bXp4V
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__y6H89
                            )}
                          >
                            {"个性化定制"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__gTn6T
                            )}
                          >
                            {
                              "个性化的定制功能，可以根据用户需求，提供量身定制的解决方案，更好地满足特定需求。"
                            }
                          </div>
                        </p.Stack>
                      </p.Stack>
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__eP7Gf
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__up9In
                          )}
                        >
                          <Icon14Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__kdMbn
                            )}
                            role={"img"}
                          />
                        </div>
                        {false ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__nov7G
                            )}
                          >
                            <Icon8Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__qFwr0
                              )}
                              role={"img"}
                            />
                          </div>
                        ) : null}
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__lzNK
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__hZUzw
                            )}
                          >
                            {"实时分析"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__nNyX
                            )}
                          >
                            {
                              "提供相关的数据分析报告和建议，协助用户做出更好的管理决策。"
                            }
                          </div>
                        </p.Stack>
                      </p.Stack>
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__xz2CT
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__jJsQd
                          )}
                        >
                          <Icon14Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__cRj0
                            )}
                            role={"img"}
                          />
                        </div>
                        {false ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___0D4Pb
                            )}
                          >
                            <Icon8Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__jala
                              )}
                              role={"img"}
                            />
                          </div>
                        ) : null}
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__lReT
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__oqnEs
                            )}
                          >
                            {"省钱省心"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__aNm39
                            )}
                          >
                            {
                              "简化写作过程，提高效率并减少错误，使得您将时间精力用在更有价值事情上，带来更好的经济回报"
                            }
                          </div>
                        </p.Stack>
                      </p.Stack>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>
              </section>
            </div>
          ) : null}
          <div
            data-plasmic-name={"price"}
            data-plasmic-override={overrides.price}
            className={classNames(projectcss.all, sty.price)}
          >
            <div className={classNames(projectcss.all, sty.freeBox___40G0O)} />
            <p.Stack
              as={"div"}
              data-plasmic-name={"foreground2"}
              data-plasmic-override={overrides.foreground2}
              hasGap={true}
              className={classNames(projectcss.all, sty.foreground2)}
              id={"price-card"}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__b70IF)}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___5KzDf)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___9HD0J
                    )}
                  >
                    {"免费加入会员，获取专属模板，提升字数额度"}
                  </div>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__l5FPi
                  )}
                >
                  {
                    "希望您的支持确保我们的产品始终处于最新状态。我们将持续优化我们的产品，为您提供最佳的用户体验。"
                  }
                </div>
              </p.Stack>
              <Price
                data-plasmic-name={"price2"}
                data-plasmic-override={overrides.price2}
                className={classNames("__wab_instance", sty.price2)}
              />
            </p.Stack>
          </div>
          <p.Stack
            as={"div"}
            data-plasmic-name={"about"}
            data-plasmic-override={overrides.about}
            hasGap={true}
            className={classNames(projectcss.all, sty.about)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"foreground3"}
              data-plasmic-override={overrides.foreground3}
              hasGap={true}
              className={classNames(projectcss.all, sty.foreground3)}
              id={"aboutus"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rfMyL
                )}
              >
                {"新时代重新出发！"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tIIzx
                )}
              >
                {"关于我们"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__sPTwg
                )}
              >
                {
                  "我们全力拥抱人工智能技术，旨在提供最优秀的工具，助力您的企业实现效率的最大化和最优化。我们致力于为您提供最新的解决方案，包括语音识别、自然语言处理、大数据分析等，让您的业务变得更加智能和高效。"
                }
              </div>
            </p.Stack>
          </p.Stack>
          <div
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames(projectcss.all, sty.footer)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"columns"}
              data-plasmic-override={overrides.columns}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns)}
            >
              <div className={classNames(projectcss.all, sty.column__deD1T)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__kIDkD)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__dTGo3)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"180px"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    src={{
                      src: "/plasmic/chats_client/images/logofull2Xpng.png",
                      fullWidth: 346,
                      fullHeight: 96,
                      aspectRatio: undefined
                    }}
                  />

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__tNcGo)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yHyWq
                      )}
                    >
                      {"联系我们"}
                    </div>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__sZ37Y)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__gepwy)}
                        role={"img"}
                      />

                      <Icon4Icon
                        className={classNames(projectcss.all, sty.svg__vkxSo)}
                        role={"img"}
                      />

                      <Icon28Icon
                        className={classNames(projectcss.all, sty.svg__tG8FM)}
                        role={"img"}
                      />
                    </p.Stack>
                  </p.Stack>
                </p.Stack>
              </div>
              <div className={classNames(projectcss.all, sty.column__kHzbo)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__tPq5K)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tdgbs
                    )}
                  >
                    {"产品"}
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button___1N0I5)}
                    color={"clear"}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__nAuG1)}
                        role={"img"}
                      />
                    }
                    onClick={async event => {
                      const $steps = {};
                      $steps["goToPriceCard"] = true
                        ? (() => {
                            const actionArgs = {
                              destination: __wrapUserFunction(
                                {
                                  type: "InteractionArgLoc",
                                  actionName: "navigation",
                                  interactionUuid: "V-t2n-yeU",
                                  componentUuid: "AAi9AuCCbMra",
                                  argName: "destination"
                                },
                                () => "/#price-card"
                              )
                            };
                            return __wrapUserFunction(
                              {
                                type: "InteractionLoc",
                                actionName: "navigation",
                                interactionUuid: "V-t2n-yeU",
                                componentUuid: "AAi9AuCCbMra"
                              },
                              () =>
                                (({ destination }) => {
                                  __nextRouter?.push(destination);
                                })?.apply(null, [actionArgs]),
                              actionArgs
                            );
                          })()
                        : undefined;
                      if (
                        typeof $steps["goToPriceCard"] === "object" &&
                        typeof $steps["goToPriceCard"].then === "function"
                      ) {
                        $steps["goToPriceCard"] = await __wrapUserPromise(
                          {
                            type: "InteractionLoc",
                            actionName: "navigation",
                            interactionUuid: "V-t2n-yeU",
                            componentUuid: "AAi9AuCCbMra"
                          },
                          $steps["goToPriceCard"]
                        );
                      }
                    }}
                    size={"minimal"}
                    startIcon={
                      <ChecksvgIcon
                        className={classNames(projectcss.all, sty.svg__zgHNf)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gKtby
                      )}
                    >
                      {"价格"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__dnsbo)}
                    color={"clear"}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__twP4S)}
                        role={"img"}
                      />
                    }
                    size={"minimal"}
                    startIcon={
                      <ChecksvgIcon
                        className={classNames(projectcss.all, sty.svg__ocgLh)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kJznj
                      )}
                    >
                      {"登录"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__szD65)}
                    color={"clear"}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__rBdXb)}
                        role={"img"}
                      />
                    }
                    size={"minimal"}
                    startIcon={
                      <ChecksvgIcon
                        className={classNames(projectcss.all, sty.svg__vT4T4)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rfyFt
                      )}
                    >
                      {"使用说明"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button___3NAr6)}
                    color={"clear"}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg___8F13T)}
                        role={"img"}
                      />
                    }
                    size={"minimal"}
                    startIcon={
                      <ChecksvgIcon
                        className={classNames(projectcss.all, sty.svg__zyLrg)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rtk4A
                      )}
                    >
                      {"关于我们"}
                    </div>
                  </Button>
                </p.Stack>
              </div>
              <div className={classNames(projectcss.all, sty.column__vH077)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__hm0IO)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__f04Hl
                    )}
                  >
                    {"Support"}
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button__gtZoB)}
                    color={"clear"}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__mNthj)}
                        role={"img"}
                      />
                    }
                    size={"minimal"}
                    startIcon={
                      <ChecksvgIcon
                        className={classNames(projectcss.all, sty.svg___11TgO)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__zPfyo
                      )}
                    >
                      {"说明文档"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button___2M31F)}
                    color={"clear"}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__qHwtp)}
                        role={"img"}
                      />
                    }
                    size={"minimal"}
                    startIcon={
                      <ChecksvgIcon
                        className={classNames(projectcss.all, sty.svg___2Ggcw)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hBcwJ
                      )}
                    >
                      {"FAQs常见问题"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__tWbr)}
                    color={"clear"}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__zzpFk)}
                        role={"img"}
                      />
                    }
                    size={"minimal"}
                    startIcon={
                      <ChecksvgIcon
                        className={classNames(projectcss.all, sty.svg__bmuoe)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__e639I
                      )}
                    >
                      {"联系方式"}
                    </div>
                  </Button>
                </p.Stack>
              </div>
            </p.Stack>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "foreground",
    "login",
    "textbox",
    "textbox2",
    "textbox3",
    "value",
    "foreground4",
    "h2",
    "price",
    "foreground2",
    "price2",
    "about",
    "foreground3",
    "footer",
    "columns"
  ],

  foreground: ["foreground", "login", "textbox", "textbox2", "textbox3"],
  login: ["login", "textbox", "textbox2", "textbox3"],
  textbox: ["textbox"],
  textbox2: ["textbox2"],
  textbox3: ["textbox3"],
  value: ["value", "foreground4", "h2"],
  foreground4: ["foreground4", "h2"],
  h2: ["h2"],
  price: ["price", "foreground2", "price2"],
  foreground2: ["foreground2", "price2"],
  price2: ["price2"],
  about: ["about", "foreground3"],
  foreground3: ["foreground3"],
  footer: ["footer", "columns"],
  columns: ["columns"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    foreground: makeNodeComponent("foreground"),
    login: makeNodeComponent("login"),
    textbox: makeNodeComponent("textbox"),
    textbox2: makeNodeComponent("textbox2"),
    textbox3: makeNodeComponent("textbox3"),
    value: makeNodeComponent("value"),
    foreground4: makeNodeComponent("foreground4"),
    h2: makeNodeComponent("h2"),
    price: makeNodeComponent("price"),
    foreground2: makeNodeComponent("foreground2"),
    price2: makeNodeComponent("price2"),
    about: makeNodeComponent("about"),
    foreground3: makeNodeComponent("foreground3"),
    footer: makeNodeComponent("footer"),
    columns: makeNodeComponent("columns"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Key-value metadata
    metadata: {
      charset: "utf-8",
      name: "viewport",
      content: "width=750,inital-scale=1.0,maximum-scale=1.0,user-scalable=no"
    },
    // Page metadata
    pageMetadata: {
      title: "机智桔子-你的AI助手",
      description: "提高产出10倍，这个AI时代，你需要新的效率工具。",
      ogImageSrc:
        "https://site-assets.plasmic.app/5a3fcd1a01a06a23046dc80f21312272.png",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
